name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create env file
      env: 
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASS: ${{ secrets.MYSQL_PASS }}
        MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
        MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
        PROD: ${{ secrets.PROD }}
      run: |
        touch .env
        echo $MYSQL_USER >> .env
        echo $MYSQL_PASS >> .env
        echo $MYSQL_HOST >> .env
        echo $MYSQL_PORT >> .env
        echo $MYSQL_DATABASE >> .env
        echo $secret.JWT_SECRET >> .env
        echo $secret.JWT_ISSUER >> .env
        echo $secret.PROD >> .env
        cat .env
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag chronicle:$(date +%s)
